# Generated by Django 4.2.2 on 2023-06-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_tag_project_vote_total_review_project_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="vote_ratio",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
